server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: env,beans

# Datasource
spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

fio:
  url: https://www.fio.cz/ib_api/rest/
  tokens:
    rosmarinusCZ: zQNZcR1HT4eSIcSl1GLC1qguLCw2kIbUd7NrG4WBAgi7syR8Op7zpvKNHYlCAx92